
# ----------------------------------------------#
# settings
# ----------------------------------------------#
PHP=php

# ----------------------------------------------#
# targets
# ----------------------------------------------#
all:
	php main.php --file version.las

debug:
	php main.php --file version.las -d

startserver:
	php -S 127.0.0.1:8000 -t public
